version: '3.4'

services:
  learning-javascript:
    image: learning-javascript
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true